
pull_request_rules:
  - name: Automated merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
    actions:
      merge:
        method: merge
      label:
        add: ["dependencies","🛠 Improvement"]

  - name: Automated dependabot merge
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge
      label:
        add: ["dependencies","🛠 Improvement"]
